### ISSUE TITLE
Ease of Navigation

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak-docs-fork#110]
Currently, there is no way to hop directly between two different products' docs. Instead you have to either click the "Riak Docs" logo or the "Riak [CURRENT RIAK PRODUCT]" logo to go back to the top page of the docs and then choose which of the products you want to switch to. This seems horribly inefficient.

As we have a huge amount of empty space at the top of the page before the links to "Community" and "Contact", why don't we have direct links in there to the latest versions of the KV, CS and TS docs in there? If the links were literally "KV", "CS", "TS" then the amount of space needed would be tiny and it would be great if we could highlight the currently open product link in the yellowy-orange colour whilst the others are in the standard light grey.

**Comment by Bob-The-Marauder** [comment]
In an update, this turns out to be caused by modern screen widths that exceed the maximum the site handles. If viewed in a window then the navigation features which actually exist show as intended. However, on wider monitors, switching to a full screen window makes them disappear.

**Comment by JMercerGit** [comment]
This issue is fixed in dev
