### ISSUE TITLE
Add documentation for bucket property `node_confirms`

### ISSUE THREAD

**Issue by JMercerGit** [TI-Tokyo/riak-docs-fork#17]
Was actually added in 2.2.5/2.2.6. But needs adding.

This feature adds a new bucket property, and write-option of `node_confirms`. Unlike w and pw that are tunables for consistency, `node_confirms` is a tunable for durability. When operating in a failure state, Riak will store replicas in fallback vnodes, and in some case multiple fallbacks may be on the same physical node. `node_confirms` is an option that specifies how many distinct physical nodes must acknowledge a write for it to be considered successful. 

Full writeup can be found at https://github.com/ramensen/riak_kv/blob/30b0e50374196d9a8cfef37871955a5f5b2bb472/docs/Node-Diversity.md

**Comment by Bob-The-Marauder** [comment]
That's bizarre. I'm sure I added this into reference somewhere for advanced.config but I can't find it anywhere.

**Comment by JMercerGit** [comment]
Sorry I only just saw this @Bob-The-Marauder . That's very odd, I cant find it anywhere in the documents.

**Comment by JMercerGit** [comment]
This issue appears to have been resolved in the /using/ section.
