### ISSUE TITLE
Out of date references still exist

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak-docs-fork#219]
https://www.tiot.jp/riak-docs/riak/kv/2.9.10/setup/upgrading/checklist/#troubleshooting-and-support asks the user if they know how to raise a ticket with Basho. Short of owning a time machine, this could be tricky and even then they wouldn't be familiar with 2.9.x either.

**Comment by pjaclark** [comment]
As we're the only people who offer enterprise-grade support we should probably update this to reflect that.

How about we replace with:

- For free support, go to the /community page to find helpful links
- To open a support ticket (which requires a support contact with TI Tokyo), go to https://support.tiot.jp/
  - This would then have the same content as the existing section.

**Comment by JMercerGit** [comment]
This issue was closed in PR #241
