### ISSUE TITLE
Some of the click to switch to OS docs don't switch back

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak-docs-fork#274]
If we look at https://www.tiot.jp/riak-docs/riak/kv/2.9.10/setup/upgrading/version/#upgrading-process for example with steps 2 and 3 (backing up stuff then removing basho-patches) we can see how we have RHEL/CentOS and Ubuntu options. The RHEL/CentOS use `/usr/lib64/...` whereas Ubuntu uses `/usr/lib/...`.

Steps to replicate:

1. Click on Ubuntu - the command changes to the Ubuntu version
2. Click back on RHEL/CentOS - for 2), the command vanishes and for 3), the command stays as the Ubuntu command i.e. `/usr/lib/...` and not `/usr/lib64/..`

I'm not sure the prevalence of this issue throughout the docs. I'd like to think it was only this page as this is the only place I have found it. However, it is possible it exists elsewhere too.

**Comment by pjaclark** [comment]
Initial guess - it's the `/` in `RHEL/CENTOS`

**Comment by pjaclark** [comment]
For code blocks, use `ubuntudebian` and `rhelcentos`.

Then in [code-blocks.coffee](https://github.com/TI-Tokyo/riak-docs-fork/blob/dev/dynamic/js/basho/code-blocks.coffee#L84) add something like:

```
  'language-ubuntudebian'     : { display_name : 'Ubuntu&#92;Debian',  highlight_as : 'language-bash' }
  'language-rhelcentos'     : { display_name : 'RHEL&#92;CentOS',  highlight_as : 'language-bash' }
```
