### ISSUE TITLE
Change riak-admin/riak-repl references in 3.0.1

### ISSUE THREAD

**Issue by JMercerGit** [TI-Tokyo/riak-docs-fork#60]
Change riak-admin/riak-repl references as in 2.9.1 these have been changed to `riak admin` and `riak repl`

**Comment by Bob-The-Marauder** [comment]
Is this accurate? I run 2.9.8 at home for random tests and occasional abuse and that accepts the regular `riak-admin` and `riak-repl`. Pretty sure that change starts from 3.0.1.

**Comment by JMercerGit** [comment]
> Is this accurate? I run 2.9.8 at home for random tests and occasional abuse and that accepts the regular `riak-admin` and `riak-repl`. Pretty sure that change starts from 3.0.1

You're right. Apparently my VM was running 3.0.3 by mistake. Thought I'd reinstalled 2.9.1
