### ISSUE TITLE
Update downloads file to reference tiot downloads links in all versions

### ISSUE THREAD

**Issue by JMercerGit** [TI-Tokyo/riak-docs-fork#64]
Update downloads file to reference tiot downloads links in all versions

**Comment by Bob-The-Marauder** [comment]
Is this for https://www.tiot.jp/riak-docs/riak/kv/2.2.6/downloads/ where all the links are broken? If so, we should push this and publish it as a priority as soon as it's fixed.

**Comment by JMercerGit** [comment]
It was for 2.9.0 +, however I can create a fix for 2.2.6 too.

**Comment by JMercerGit** [comment]
This seems to be fixed in the version of the files for 2.2. 6 from github.
