### ISSUE TITLE
Actual examples too shallow

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak-docs-fork#67]
Quite a lot of the reference materials in the docs say "run `riak-admin transfers`" for example but there is no indication I can find of what the expected output actually is. Although it will be a nightmare to fix, including examples of the different return states for all commands would be beneficial to general users for reference and for us when we can't immidiately stand up a cluster to get sample outputs needed for ticket replies

**Comment by JMercerGit** [comment]
I feel like covering the basics (IE, expected outputs should b XYZ) would be the best approach, rather than trying to cover every eventuality
