### ISSUE TITLE
docker-compose.localhost-preview.yaml does not exist

### ISSUE THREAD

**Issue by meangrape** [TI-Tokyo/riak-docs-fork#90]
When following the instructions in `README.md` to build and test documentation locally, item 4 says:

```
Run the docker image as a local server to test it all works:
docker-compose -f ./docker/docker-compose.localhost-preview.yaml up riakdocs
```

This file doesn't exist and, apparently, has never existed.
`git log --all --follow --full-history -- docker-compose.localhost-preview.yaml` has no results.

The closest file is `docker-compose.localhost.yaml`

**Comment by pjaclark** [comment]
That looks right. I think whilst updating the readme I renamed the file to make it clearer that it was a preview and not suitable for live use, and then promptly forgot to rename the actual file. I'll rename the file to match the readme, as I like the clarity in the name. 

On that note, I should probably rename `docker-compose.generate-riak-docs.yaml` (and beta version) to reflect that it's only for `www.tiot.jp/riak-docs`, and update the guide for how to make one for other systems. 

I should also add one for `docs.riak.com` and `www.riak.info/riak-docs/` too. I haven't done that yet, as I wanted to get the themes working before pushing to `basho/basho_docs`.
