### ISSUE TITLE
Wrong package link from the docs.

### ISSUE THREAD

**Issue by JMercerGit** [TI-Tokyo/riak-docs-fork#99]
From the following documentation link: https://www.tiot.jp/riak-docs/riak/kv/2.9.10/setup/installing/debian-ubuntu/, the package link is incorrect.

It is currently https://files.tiot.jp/riak/kv/2.2/2.9.10/debian/8/riak_2.9.0-1_amd64.deb where it should have been https://files.tiot.jp/riak/kv/2.9/2.9.10/ubuntu/bionic64/riak_2.9.10-1_amd64.deb.

**Comment by pjaclark** [comment]
Updated in dev.
